name: Linting

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore: [ v.* ]

jobs:
  prose:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v3.5.0
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3

      # https://vale.sh
      - name: Vale
        # https://github.com/errata-ai/vale-action/releases
        # v2.0.1
        uses: errata-ai/vale-action@c4213d4de3d5f718b8497bd86161531c78992084
        with:
          files: '["docs/dev", "docs/src", "samples"]'
          fail_on_error: true
          filter_mode: nofilter
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
