name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"

  deploy-create-akkasls-entity:
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        working-directory: create-akkasls-entity

    steps:
      - name: Set version
        run: 'sed -i "s/  \"version\":.*/  \"version\": \"$(git tag|cut -c2-)\",/" package.json'
      - run: npm install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  deploy-akkasls-scripts:
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        working-directory: akkasls-scripts

    steps:
      - name: Set version
        run: 'sed -i "s/  \"version\":.*/  \"version\": \"$(git tag|cut -c2-)\",/" package.json'
      - run: npm install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
